const Ziggy = {
  url: 'http:\/\/localhost:8000',
  port: 8000,
  defaults: {},
  routes: {
    'boost.browser-logs': { uri: '_boost\/browser-logs', methods: ['POST'] },
    'sanctum.csrf-cookie': { uri: 'sanctum\/csrf-cookie', methods: ['GET', 'HEAD'] },
    dashboard: { uri: 'tooldock\/dashboard', methods: ['GET', 'HEAD'] },
    'profile.edit': { uri: 'tooldock\/profile', methods: ['GET', 'HEAD'] },
    'profile.update': { uri: 'tooldock\/profile', methods: ['PATCH'] },
    'profile.destroy': { uri: 'tooldock\/profile', methods: ['DELETE'] },
    register: { uri: 'tooldock\/register', methods: ['GET', 'HEAD'] },
    login: { uri: 'tooldock\/login', methods: ['GET', 'HEAD'] },
    'password.request': { uri: 'tooldock\/forgot-password', methods: ['GET', 'HEAD'] },
    'password.email': { uri: 'tooldock\/forgot-password', methods: ['POST'] },
    'password.reset': {
      uri: 'tooldock\/reset-password\/{token}',
      methods: ['GET', 'HEAD'],
      parameters: ['token'],
    },
    'password.store': { uri: 'tooldock\/reset-password', methods: ['POST'] },
    'verification.notice': { uri: 'tooldock\/verify-email', methods: ['GET', 'HEAD'] },
    'verification.verify': {
      uri: 'tooldock\/verify-email\/{id}\/{hash}',
      methods: ['GET', 'HEAD'],
      parameters: ['id', 'hash'],
    },
    'verification.send': { uri: 'tooldock\/email\/verification-notification', methods: ['POST'] },
    'password.confirm': { uri: 'tooldock\/confirm-password', methods: ['GET', 'HEAD'] },
    'password.update': { uri: 'tooldock\/password', methods: ['PUT'] },
    logout: { uri: 'tooldock\/logout', methods: ['POST'] },
    'storage.local': {
      uri: 'storage\/{path}',
      methods: ['GET', 'HEAD'],
      wheres: { path: '.*' },
      parameters: ['path'],
    },
    'api.core.index': { uri: 'api\/v1\/cores', methods: ['GET', 'HEAD'] },
    'api.core.store': { uri: 'api\/v1\/cores', methods: ['POST'] },
    'api.core.show': {
      uri: 'api\/v1\/cores\/{core}',
      methods: ['GET', 'HEAD'],
      parameters: ['core'],
    },
    'api.core.update': {
      uri: 'api\/v1\/cores\/{core}',
      methods: ['PUT', 'PATCH'],
      parameters: ['core'],
    },
    'api.core.destroy': {
      uri: 'api\/v1\/cores\/{core}',
      methods: ['DELETE'],
      parameters: ['core'],
    },
    'core.users.index': { uri: 'tooldock\/users', methods: ['GET', 'HEAD'] },
    'core.users.create': { uri: 'tooldock\/users\/create', methods: ['GET', 'HEAD'] },
    'core.users.store': { uri: 'tooldock\/users', methods: ['POST'] },
    'core.users.show': {
      uri: 'tooldock\/users\/{user}',
      methods: ['GET', 'HEAD'],
      parameters: ['user'],
    },
    'core.users.edit': {
      uri: 'tooldock\/users\/{user}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['user'],
      bindings: { user: 'id' },
    },
    'core.users.update': {
      uri: 'tooldock\/users\/{user}',
      methods: ['PUT', 'PATCH'],
      parameters: ['user'],
      bindings: { user: 'id' },
    },
    'core.users.destroy': {
      uri: 'tooldock\/users\/{user}',
      methods: ['DELETE'],
      parameters: ['user'],
      bindings: { user: 'id' },
    },
    'core.roles.index': { uri: 'tooldock\/roles', methods: ['GET', 'HEAD'] },
    'core.roles.create': { uri: 'tooldock\/roles\/create', methods: ['GET', 'HEAD'] },
    'core.roles.store': { uri: 'tooldock\/roles', methods: ['POST'] },
    'core.roles.show': {
      uri: 'tooldock\/roles\/{role}',
      methods: ['GET', 'HEAD'],
      parameters: ['role'],
    },
    'core.roles.edit': {
      uri: 'tooldock\/roles\/{role}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['role'],
      bindings: { role: 'id' },
    },
    'core.roles.update': {
      uri: 'tooldock\/roles\/{role}',
      methods: ['PUT', 'PATCH'],
      parameters: ['role'],
      bindings: { role: 'id' },
    },
    'core.roles.destroy': {
      uri: 'tooldock\/roles\/{role}',
      methods: ['DELETE'],
      parameters: ['role'],
      bindings: { role: 'id' },
    },
    'core.modules.index': { uri: 'tooldock\/modules', methods: ['GET', 'HEAD'] },
    'core.modules.install': { uri: 'tooldock\/modules\/install', methods: ['POST'] },
    'core.modules.uninstall': { uri: 'tooldock\/modules\/uninstall', methods: ['POST'] },
    'core.modules.toggle': { uri: 'tooldock\/modules\/toggle', methods: ['POST'] },
    'core.dashboard': { uri: 'tooldock\/core\/dashboard', methods: ['GET', 'HEAD'] },
  },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
  Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
