const Ziggy = {
  url: 'http:\/\/localhost:8000',
  port: 8000,
  defaults: {},
  routes: {
    'boost.browser-logs': { uri: '_boost\/browser-logs', methods: ['POST'] },
    'sanctum.csrf-cookie': { uri: 'sanctum\/csrf-cookie', methods: ['GET', 'HEAD'] },
    dashboard: { uri: 'tooldock\/dashboard', methods: ['GET', 'HEAD'] },
    'profile.edit': { uri: 'tooldock\/profile', methods: ['GET', 'HEAD'] },
    'profile.update': { uri: 'tooldock\/profile', methods: ['PATCH'] },
    'profile.destroy': { uri: 'tooldock\/profile', methods: ['DELETE'] },
    register: { uri: 'tooldock\/register', methods: ['GET', 'HEAD'] },
    login: { uri: 'tooldock\/login', methods: ['GET', 'HEAD'] },
    'password.request': { uri: 'tooldock\/forgot-password', methods: ['GET', 'HEAD'] },
    'password.email': { uri: 'tooldock\/forgot-password', methods: ['POST'] },
    'password.reset': {
      uri: 'tooldock\/reset-password\/{token}',
      methods: ['GET', 'HEAD'],
      parameters: ['token'],
    },
    'password.store': { uri: 'tooldock\/reset-password', methods: ['POST'] },
    'verification.notice': { uri: 'tooldock\/verify-email', methods: ['GET', 'HEAD'] },
    'verification.verify': {
      uri: 'tooldock\/verify-email\/{id}\/{hash}',
      methods: ['GET', 'HEAD'],
      parameters: ['id', 'hash'],
    },
    'verification.send': { uri: 'tooldock\/email\/verification-notification', methods: ['POST'] },
    'password.confirm': { uri: 'tooldock\/confirm-password', methods: ['GET', 'HEAD'] },
    'password.update': { uri: 'tooldock\/password', methods: ['PUT'] },
    logout: { uri: 'tooldock\/logout', methods: ['POST'] },
    'api.core.index': { uri: 'api\/v1\/cores', methods: ['GET', 'HEAD'] },
    'api.core.store': { uri: 'api\/v1\/cores', methods: ['POST'] },
    'api.core.show': {
      uri: 'api\/v1\/cores\/{core}',
      methods: ['GET', 'HEAD'],
      parameters: ['core'],
    },
    'api.core.update': {
      uri: 'api\/v1\/cores\/{core}',
      methods: ['PUT', 'PATCH'],
      parameters: ['core'],
    },
    'api.core.destroy': {
      uri: 'api\/v1\/cores\/{core}',
      methods: ['DELETE'],
      parameters: ['core'],
    },
    'core.users.index': { uri: 'tooldock\/users', methods: ['GET', 'HEAD'] },
    'core.users.create': { uri: 'tooldock\/users\/create', methods: ['GET', 'HEAD'] },
    'core.users.store': { uri: 'tooldock\/users', methods: ['POST'] },
    'core.users.show': {
      uri: 'tooldock\/users\/{user}',
      methods: ['GET', 'HEAD'],
      parameters: ['user'],
    },
    'core.users.edit': {
      uri: 'tooldock\/users\/{user}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['user'],
      bindings: { user: 'id' },
    },
    'core.users.update': {
      uri: 'tooldock\/users\/{user}',
      methods: ['PUT', 'PATCH'],
      parameters: ['user'],
      bindings: { user: 'id' },
    },
    'core.users.destroy': {
      uri: 'tooldock\/users\/{user}',
      methods: ['DELETE'],
      parameters: ['user'],
      bindings: { user: 'id' },
    },
    'core.roles.index': { uri: 'tooldock\/roles', methods: ['GET', 'HEAD'] },
    'core.roles.create': { uri: 'tooldock\/roles\/create', methods: ['GET', 'HEAD'] },
    'core.roles.store': { uri: 'tooldock\/roles', methods: ['POST'] },
    'core.roles.show': {
      uri: 'tooldock\/roles\/{role}',
      methods: ['GET', 'HEAD'],
      parameters: ['role'],
    },
    'core.roles.edit': {
      uri: 'tooldock\/roles\/{role}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['role'],
      bindings: { role: 'id' },
    },
    'core.roles.update': {
      uri: 'tooldock\/roles\/{role}',
      methods: ['PUT', 'PATCH'],
      parameters: ['role'],
      bindings: { role: 'id' },
    },
    'core.roles.destroy': {
      uri: 'tooldock\/roles\/{role}',
      methods: ['DELETE'],
      parameters: ['role'],
      bindings: { role: 'id' },
    },
    'core.modules.index': { uri: 'tooldock\/modules', methods: ['GET', 'HEAD'] },
    'core.modules.install': { uri: 'tooldock\/modules\/install', methods: ['POST'] },
    'core.modules.uninstall': { uri: 'tooldock\/modules\/uninstall', methods: ['POST'] },
    'core.modules.toggle': { uri: 'tooldock\/modules\/toggle', methods: ['POST'] },
    'core.dashboard': { uri: 'tooldock\/core\/dashboard', methods: ['GET', 'HEAD'] },
    'api.settings.index': { uri: 'api\/v1\/settings', methods: ['GET', 'HEAD'] },
    'api.settings.store': { uri: 'api\/v1\/settings', methods: ['POST'] },
    'api.settings.show': {
      uri: 'api\/v1\/settings\/{setting}',
      methods: ['GET', 'HEAD'],
      parameters: ['setting'],
    },
    'api.settings.update': {
      uri: 'api\/v1\/settings\/{setting}',
      methods: ['PUT', 'PATCH'],
      parameters: ['setting'],
    },
    'api.settings.destroy': {
      uri: 'api\/v1\/settings\/{setting}',
      methods: ['DELETE'],
      parameters: ['setting'],
    },
    'settings.index': { uri: 'tooldock\/settings', methods: ['GET', 'HEAD'] },
    'settings.update': { uri: 'tooldock\/settings', methods: ['PATCH'] },
    'settings.dashboard': { uri: 'tooldock\/settings\/dashboard', methods: ['GET', 'HEAD'] },
    'api.auditlog.index': { uri: 'api\/v1\/auditlogs', methods: ['GET', 'HEAD'] },
    'api.auditlog.store': { uri: 'api\/v1\/auditlogs', methods: ['POST'] },
    'api.auditlog.show': {
      uri: 'api\/v1\/auditlogs\/{auditlog}',
      methods: ['GET', 'HEAD'],
      parameters: ['auditlog'],
    },
    'api.auditlog.update': {
      uri: 'api\/v1\/auditlogs\/{auditlog}',
      methods: ['PUT', 'PATCH'],
      parameters: ['auditlog'],
    },
    'api.auditlog.destroy': {
      uri: 'api\/v1\/auditlogs\/{auditlog}',
      methods: ['DELETE'],
      parameters: ['auditlog'],
    },
    'auditlog.index': { uri: 'tooldock\/audit-logs', methods: ['GET', 'HEAD'] },
    'auditlog.show': {
      uri: 'tooldock\/audit-logs\/{auditLog}',
      methods: ['GET', 'HEAD'],
      parameters: ['auditLog'],
      bindings: { auditLog: 'id' },
    },
    'auditlog.export': { uri: 'tooldock\/audit-logs\/export\/csv', methods: ['GET', 'HEAD'] },
    'auditlog.dashboard': { uri: 'tooldock\/auditlog\/dashboard', methods: ['GET', 'HEAD'] },
    'api.categories.index': { uri: 'api\/v1\/categories', methods: ['GET', 'HEAD'] },
    'api.categories.store': { uri: 'api\/v1\/categories', methods: ['POST'] },
    'api.categories.show': {
      uri: 'api\/v1\/categories\/{category}',
      methods: ['GET', 'HEAD'],
      parameters: ['category'],
    },
    'api.categories.update': {
      uri: 'api\/v1\/categories\/{category}',
      methods: ['PUT', 'PATCH'],
      parameters: ['category'],
      bindings: { category: 'id' },
    },
    'api.categories.destroy': {
      uri: 'api\/v1\/categories\/{category}',
      methods: ['DELETE'],
      parameters: ['category'],
      bindings: { category: 'id' },
    },
    'categories.index': { uri: 'tooldock\/categories', methods: ['GET', 'HEAD'] },
    'categories.create': { uri: 'tooldock\/categories\/create', methods: ['GET', 'HEAD'] },
    'categories.store': { uri: 'tooldock\/categories', methods: ['POST'] },
    'categories.edit': {
      uri: 'tooldock\/categories\/{category}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['category'],
      bindings: { category: 'id' },
    },
    'categories.update': {
      uri: 'tooldock\/categories\/{category}',
      methods: ['PUT', 'PATCH'],
      parameters: ['category'],
      bindings: { category: 'id' },
    },
    'categories.destroy': {
      uri: 'tooldock\/categories\/{category}',
      methods: ['DELETE'],
      parameters: ['category'],
      bindings: { category: 'id' },
    },
    'categories.dashboard': { uri: 'tooldock\/categories\/dashboard', methods: ['GET', 'HEAD'] },
    'api.media.upload-temporary': { uri: 'api\/v1\/media\/upload-temporary', methods: ['POST'] },
    'api.media.upload': { uri: 'api\/v1\/media\/upload', methods: ['POST'] },
    'media.index': { uri: 'tooldock\/media', methods: ['GET', 'HEAD'] },
    'media.destroy': {
      uri: 'tooldock\/media\/{medium}',
      methods: ['DELETE'],
      parameters: ['medium'],
      bindings: { medium: 'id' },
    },
    'media.dashboard': { uri: 'tooldock\/media\/dashboard', methods: ['GET', 'HEAD'] },
    'storage.local': {
      uri: 'storage\/{path}',
      methods: ['GET', 'HEAD'],
      wheres: { path: '.*' },
      parameters: ['path'],
    },
  },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
  Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
