const Ziggy = {
  url: 'http:\/\/localhost:8000',
  port: 8000,
  defaults: {},
  routes: {
    'boost.browser-logs': { uri: '_boost\/browser-logs', methods: ['POST'] },
    'sanctum.csrf-cookie': { uri: 'sanctum\/csrf-cookie', methods: ['GET', 'HEAD'] },
    dashboard: { uri: 'dashboard', methods: ['GET', 'HEAD'] },
    'profile.edit': { uri: 'profile', methods: ['GET', 'HEAD'] },
    'profile.update': { uri: 'profile', methods: ['PATCH'] },
    'profile.destroy': { uri: 'profile', methods: ['DELETE'] },
    register: { uri: 'register', methods: ['GET', 'HEAD'] },
    login: { uri: 'login', methods: ['GET', 'HEAD'] },
    'password.request': { uri: 'forgot-password', methods: ['GET', 'HEAD'] },
    'password.email': { uri: 'forgot-password', methods: ['POST'] },
    'password.reset': {
      uri: 'reset-password\/{token}',
      methods: ['GET', 'HEAD'],
      parameters: ['token'],
    },
    'password.store': { uri: 'reset-password', methods: ['POST'] },
    'verification.notice': { uri: 'verify-email', methods: ['GET', 'HEAD'] },
    'verification.verify': {
      uri: 'verify-email\/{id}\/{hash}',
      methods: ['GET', 'HEAD'],
      parameters: ['id', 'hash'],
    },
    'verification.send': { uri: 'email\/verification-notification', methods: ['POST'] },
    'password.confirm': { uri: 'confirm-password', methods: ['GET', 'HEAD'] },
    'password.update': { uri: 'password', methods: ['PUT'] },
    logout: { uri: 'logout', methods: ['POST'] },
    'api.core.index': { uri: 'api\/v1\/cores', methods: ['GET', 'HEAD'] },
    'api.core.store': { uri: 'api\/v1\/cores', methods: ['POST'] },
    'api.core.show': {
      uri: 'api\/v1\/cores\/{core}',
      methods: ['GET', 'HEAD'],
      parameters: ['core'],
    },
    'api.core.update': {
      uri: 'api\/v1\/cores\/{core}',
      methods: ['PUT', 'PATCH'],
      parameters: ['core'],
    },
    'api.core.destroy': {
      uri: 'api\/v1\/cores\/{core}',
      methods: ['DELETE'],
      parameters: ['core'],
    },
    'core.users.index': { uri: 'users', methods: ['GET', 'HEAD'] },
    'core.users.create': { uri: 'users\/create', methods: ['GET', 'HEAD'] },
    'core.users.store': { uri: 'users', methods: ['POST'] },
    'core.users.show': { uri: 'users\/{user}', methods: ['GET', 'HEAD'], parameters: ['user'] },
    'core.users.edit': {
      uri: 'users\/{user}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['user'],
      bindings: { user: 'id' },
    },
    'core.users.update': {
      uri: 'users\/{user}',
      methods: ['PUT', 'PATCH'],
      parameters: ['user'],
      bindings: { user: 'id' },
    },
    'core.users.destroy': {
      uri: 'users\/{user}',
      methods: ['DELETE'],
      parameters: ['user'],
      bindings: { user: 'id' },
    },
    'core.roles.index': { uri: 'roles', methods: ['GET', 'HEAD'] },
    'core.roles.create': { uri: 'roles\/create', methods: ['GET', 'HEAD'] },
    'core.roles.store': { uri: 'roles', methods: ['POST'] },
    'core.roles.show': { uri: 'roles\/{role}', methods: ['GET', 'HEAD'], parameters: ['role'] },
    'core.roles.edit': {
      uri: 'roles\/{role}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['role'],
      bindings: { role: 'id' },
    },
    'core.roles.update': {
      uri: 'roles\/{role}',
      methods: ['PUT', 'PATCH'],
      parameters: ['role'],
      bindings: { role: 'id' },
    },
    'core.roles.destroy': {
      uri: 'roles\/{role}',
      methods: ['DELETE'],
      parameters: ['role'],
      bindings: { role: 'id' },
    },
    'api.settings.index': { uri: 'api\/v1\/settings', methods: ['GET', 'HEAD'] },
    'api.settings.store': { uri: 'api\/v1\/settings', methods: ['POST'] },
    'api.settings.show': {
      uri: 'api\/v1\/settings\/{setting}',
      methods: ['GET', 'HEAD'],
      parameters: ['setting'],
    },
    'api.settings.update': {
      uri: 'api\/v1\/settings\/{setting}',
      methods: ['PUT', 'PATCH'],
      parameters: ['setting'],
    },
    'api.settings.destroy': {
      uri: 'api\/v1\/settings\/{setting}',
      methods: ['DELETE'],
      parameters: ['setting'],
    },
    'settings.index': { uri: 'settings', methods: ['GET', 'HEAD'] },
    'settings.update': { uri: 'settings', methods: ['PATCH'] },
    'api.blog.index': { uri: 'api\/v1\/blogs', methods: ['GET', 'HEAD'] },
    'api.blog.store': { uri: 'api\/v1\/blogs', methods: ['POST'] },
    'api.blog.show': {
      uri: 'api\/v1\/blogs\/{blog}',
      methods: ['GET', 'HEAD'],
      parameters: ['blog'],
      bindings: { blog: 'id' },
    },
    'api.blog.update': {
      uri: 'api\/v1\/blogs\/{blog}',
      methods: ['PUT', 'PATCH'],
      parameters: ['blog'],
      bindings: { blog: 'id' },
    },
    'api.blog.destroy': {
      uri: 'api\/v1\/blogs\/{blog}',
      methods: ['DELETE'],
      parameters: ['blog'],
      bindings: { blog: 'id' },
    },
    'blog.index': { uri: 'blog', methods: ['GET', 'HEAD'] },
    'blog.create': { uri: 'blog\/create', methods: ['GET', 'HEAD'] },
    'blog.store': { uri: 'blog', methods: ['POST'] },
    'blog.show': {
      uri: 'blog\/{blog}',
      methods: ['GET', 'HEAD'],
      parameters: ['blog'],
      bindings: { blog: 'id' },
    },
    'blog.edit': {
      uri: 'blog\/{blog}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['blog'],
      bindings: { blog: 'id' },
    },
    'blog.update': {
      uri: 'blog\/{blog}',
      methods: ['PUT', 'PATCH'],
      parameters: ['blog'],
      bindings: { blog: 'id' },
    },
    'blog.destroy': {
      uri: 'blog\/{blog}',
      methods: ['DELETE'],
      parameters: ['blog'],
      bindings: { blog: 'id' },
    },
    'storage.local': {
      uri: 'storage\/{path}',
      methods: ['GET', 'HEAD'],
      wheres: { path: '.*' },
      parameters: ['path'],
    },
    'api.newsletter.index': { uri: 'api\/v1\/newsletters', methods: ['GET', 'HEAD'] },
    'api.newsletter.store': { uri: 'api\/v1\/newsletters', methods: ['POST'] },
    'api.newsletter.show': {
      uri: 'api\/v1\/newsletters\/{newsletter}',
      methods: ['GET', 'HEAD'],
      parameters: ['newsletter'],
    },
    'api.newsletter.update': {
      uri: 'api\/v1\/newsletters\/{newsletter}',
      methods: ['PUT', 'PATCH'],
      parameters: ['newsletter'],
    },
    'api.newsletter.destroy': {
      uri: 'api\/v1\/newsletters\/{newsletter}',
      methods: ['DELETE'],
      parameters: ['newsletter'],
    },
    'newsletter.index': { uri: 'newsletter', methods: ['GET', 'HEAD'] },
    'newsletter.create': { uri: 'newsletter\/create', methods: ['GET', 'HEAD'] },
    'newsletter.store': { uri: 'newsletter', methods: ['POST'] },
    'newsletter.show': {
      uri: 'newsletter\/{newsletter}',
      methods: ['GET', 'HEAD'],
      parameters: ['newsletter'],
      bindings: { newsletter: 'id' },
    },
    'newsletter.edit': {
      uri: 'newsletter\/{newsletter}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['newsletter'],
      bindings: { newsletter: 'id' },
    },
    'newsletter.update': {
      uri: 'newsletter\/{newsletter}',
      methods: ['PUT', 'PATCH'],
      parameters: ['newsletter'],
      bindings: { newsletter: 'id' },
    },
    'newsletter.destroy': {
      uri: 'newsletter\/{newsletter}',
      methods: ['DELETE'],
      parameters: ['newsletter'],
      bindings: { newsletter: 'id' },
    },
    'newsletter.send': {
      uri: 'newsletter\/{newsletter}\/send',
      methods: ['POST'],
      parameters: ['newsletter'],
      bindings: { newsletter: 'id' },
    },
  },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
  Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
