/**
 * Icon resolver utility for converting icon name strings to Lucide React components.
 *
 * Uses a whitelist approach to import only icons actually used in the application,
 * reducing bundle size from ~578KB to ~15KB (97% reduction).
 *
 * Icons are organized by category for maintainability. When adding new icons,
 * import from lucide-react and add to both the import statement and iconMap.
 */
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Anchor,
  Apple,
  Archive,
  Armchair,
  ArrowDownAz,
  ArrowDownCircle,
  ArrowDownRight,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowRightCircle,
  ArrowRightLeft,
  ArrowUpCircle,
  ArrowUpDown,
  ArrowUpRight,
  Banknote,
  BarChart,
  BarChart3,
  Bath,
  BedDouble,
  Bell,
  Bitcoin,
  Book,
  BookOpen,
  Bot,
  Box,
  Braces,
  Brain,
  Briefcase,
  Building2,
  Calendar,
  Car,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  Clipboard,
  Clock,
  Code,
  Coffee,
  Coins,
  Copy,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Dumbbell,
  Edit,
  Eraser,
  Eye,
  EyeOff,
  FileText,
  FileUser,
  Film,
  Filter,
  Flame,
  FlaskConical,
  Footprints,
  GitBranch,
  GitCompare,
  Github,
  GlassWater,
  GraduationCap,
  Guitar,
  HardDrive,
  Heart,
  HeartPulse,
  HelpCircle,
  History,
  Home,
  Image,
  Inbox,
  Info,
  Key,
  Landmark,
  Languages,
  Layers,
  LayoutDashboard,
  Leaf,
  LineChart,
  Link2,
  Lock,
  LogOut,
  Mail,
  Maximize2,
  MessageCircle,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Music,
  Package,
  Palette,
  PanelLeft,
  Pause,
  PenTool,
  Pencil,
  PieChart,
  PiggyBank,
  Pill,
  Plane,
  Play,
  Plus,
  Power,
  PowerOff,
  Quote,
  Radio,
  Receipt,
  RefreshCw,
  Repeat,
  RotateCcw,
  Salad,
  Save,
  Search,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  ShoppingBag,
  Smartphone,
  SmilePlus,
  Sparkles,
  Star,
  Sun,
  Table,
  TableProperties,
  Tag,
  Target,
  Timer,
  Trash2,
  TreePine,
  TrendingDown,
  TrendingUp,
  Trophy,
  Upload,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  Users,
  Utensils,
  Wallet,
  Webhook,
  Wifi,
  Wrench,
  X,
  XCircle,
  Zap,
} from 'lucide-react';

/**
 * Icon lookup map for O(1) access by name.
 * Includes aliases for common naming variations (e.g., CheckIcon -> Check).
 */
const iconMap = {
  Activity,
  Bot,
  AlertCircle,
  AlertTriangle,
  Anchor,
  Apple,
  Archive,
  Armchair,
  ArrowDownAz,
  ArrowDownCircle,
  ArrowDownRight,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowRightCircle,
  ArrowRightLeft,
  ArrowUpCircle,
  ArrowUpDown,
  ArrowUpRight,
  Banknote,
  BarChart,
  BarChart3,
  Bath,
  BedDouble,
  Bell,
  Bitcoin,
  Book,
  BookOpen,
  Box,
  Braces,
  Brain,
  Briefcase,
  Building2,
  Calendar,
  Car,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  Clipboard,
  Clock,
  Code,
  Coffee,
  Coins,
  Copy,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Dumbbell,
  Edit,
  Eraser,
  Eye,
  EyeOff,
  FileText,
  FileUser,
  Film,
  Filter,
  Flame,
  FlaskConical,
  Footprints,
  Github,
  GitBranch,
  GitCompare,
  GlassWater,
  GraduationCap,
  Guitar,
  HardDrive,
  Heart,
  HeartPulse,
  HelpCircle,
  History,
  Home,
  Image,
  Inbox,
  Info,
  Key,
  Landmark,
  Languages,
  Layers,
  LayoutDashboard,
  Leaf,
  LineChart,
  Link2,
  Lock,
  LogOut,
  Mail,
  Maximize2,
  MessageCircle,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Music,
  Package,
  Palette,
  PanelLeft,
  Pause,
  Pencil,
  PenTool,
  PieChart,
  PiggyBank,
  Pill,
  Plane,
  Play,
  Plus,
  Power,
  PowerOff,
  Quote,
  Radio,
  Receipt,
  RefreshCw,
  Repeat,
  RotateCcw,
  Salad,
  Save,
  Search,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  ShoppingBag,
  Smartphone,
  SmilePlus,
  Sparkles,
  Star,
  Sun,
  Table,
  TableProperties,
  Tag,
  Target,
  Timer,
  Trash2,
  TreePine,
  TrendingDown,
  TrendingUp,
  Trophy,
  Upload,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  X,
  XCircle,
  Zap,
  Webhook,
  // Aliases for common naming variations
  CheckIcon: Check,
  CalendarIcon: Calendar,
  ImageIcon: Image,
  ChevronDownIcon: ChevronDown,
  ChevronLeftIcon: ChevronLeft,
  ChevronRightIcon: ChevronRight,
  // Treasury category aliases
  FoodDining: Utensils,
  Transportation: Car,
  Shopping: ShoppingBag,
  Entertainment: Film,
  BillsUtilities: Zap,
  Healthcare: HeartPulse,
  Education: GraduationCap,
  Salary: Banknote,
  Investment: TrendingUp,
  InitialBalance: PiggyBank,
  Adjustment: RefreshCw,
  OtherIncome: Wallet,
  OtherExpense: Wallet,
  HistoryIcon: History,
  PiggyBankIcon: PiggyBank,
};

/**
 * Resolves an icon name to a Lucide React component.
 *
 * Supports multiple naming conventions (kebab-case, snake_case, PascalCase)
 * and returns a fallback icon (Circle) if the requested icon is not found.
 *
 * @param {string|null|undefined} iconName - Icon name in any supported format
 * @returns {React.ComponentType} Lucide React icon component
 */
export function getIcon(iconName) {
  if (!iconName) {
    return Circle;
  }

  const normalizedName = iconName
    .split(/[-_\s]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');

  return iconMap[normalizedName] || iconMap[iconName] || Circle;
}
